// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: products/v1/products.proto

package productsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_products_v1_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_products_v1_products_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_products_v1_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_products_v1_products_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetAllProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllProductsRequest) Reset() {
	*x = GetAllProductsRequest{}
	mi := &file_products_v1_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProductsRequest) ProtoMessage() {}

func (x *GetAllProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProductsRequest.ProtoReflect.Descriptor instead.
func (*GetAllProductsRequest) Descriptor() ([]byte, []int) {
	return file_products_v1_products_proto_rawDescGZIP(), []int{2}
}

type GetAllProductsRespone struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Products      []*CreateProductResponse `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllProductsRespone) Reset() {
	*x = GetAllProductsRespone{}
	mi := &file_products_v1_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllProductsRespone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllProductsRespone) ProtoMessage() {}

func (x *GetAllProductsRespone) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllProductsRespone.ProtoReflect.Descriptor instead.
func (*GetAllProductsRespone) Descriptor() ([]byte, []int) {
	return file_products_v1_products_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllProductsRespone) GetProducts() []*CreateProductResponse {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_products_v1_products_proto protoreflect.FileDescriptor

const file_products_v1_products_proto_rawDesc = "" +
	"\n" +
	"\x1aproducts/v1/products.proto\x12\x11proto.products.v1\"*\n" +
	"\x14CreateProductRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\";\n" +
	"\x15CreateProductResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\x17\n" +
	"\x15GetAllProductsRequest\"]\n" +
	"\x15GetAllProductsRespone\x12D\n" +
	"\bproducts\x18\x01 \x03(\v2(.proto.products.v1.CreateProductResponseR\bproducts2\xde\x01\n" +
	"\x0eProductService\x12f\n" +
	"\x0eGetAllProducts\x12(.proto.products.v1.GetAllProductsRequest\x1a(.proto.products.v1.GetAllProductsRespone\"\x00\x12d\n" +
	"\rCreateProduct\x12'.proto.products.v1.CreateProductRequest\x1a(.proto.products.v1.CreateProductResponse\"\x00B\"Z myapp/api/products/v1;productsv1b\x06proto3"

var (
	file_products_v1_products_proto_rawDescOnce sync.Once
	file_products_v1_products_proto_rawDescData []byte
)

func file_products_v1_products_proto_rawDescGZIP() []byte {
	file_products_v1_products_proto_rawDescOnce.Do(func() {
		file_products_v1_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_v1_products_proto_rawDesc), len(file_products_v1_products_proto_rawDesc)))
	})
	return file_products_v1_products_proto_rawDescData
}

var file_products_v1_products_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_products_v1_products_proto_goTypes = []any{
	(*CreateProductRequest)(nil),  // 0: proto.products.v1.CreateProductRequest
	(*CreateProductResponse)(nil), // 1: proto.products.v1.CreateProductResponse
	(*GetAllProductsRequest)(nil), // 2: proto.products.v1.GetAllProductsRequest
	(*GetAllProductsRespone)(nil), // 3: proto.products.v1.GetAllProductsRespone
}
var file_products_v1_products_proto_depIdxs = []int32{
	1, // 0: proto.products.v1.GetAllProductsRespone.products:type_name -> proto.products.v1.CreateProductResponse
	2, // 1: proto.products.v1.ProductService.GetAllProducts:input_type -> proto.products.v1.GetAllProductsRequest
	0, // 2: proto.products.v1.ProductService.CreateProduct:input_type -> proto.products.v1.CreateProductRequest
	3, // 3: proto.products.v1.ProductService.GetAllProducts:output_type -> proto.products.v1.GetAllProductsRespone
	1, // 4: proto.products.v1.ProductService.CreateProduct:output_type -> proto.products.v1.CreateProductResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_products_v1_products_proto_init() }
func file_products_v1_products_proto_init() {
	if File_products_v1_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_v1_products_proto_rawDesc), len(file_products_v1_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_v1_products_proto_goTypes,
		DependencyIndexes: file_products_v1_products_proto_depIdxs,
		MessageInfos:      file_products_v1_products_proto_msgTypes,
	}.Build()
	File_products_v1_products_proto = out.File
	file_products_v1_products_proto_goTypes = nil
	file_products_v1_products_proto_depIdxs = nil
}
