// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: users/v1/users.proto

package usersv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "myapp/api/users/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// UsersServiceName is the fully-qualified name of the UsersService service.
	UsersServiceName = "proto.users.v1.UsersService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// UsersServiceGetAllUsersProcedure is the fully-qualified name of the UsersService's GetAllUsers
	// RPC.
	UsersServiceGetAllUsersProcedure = "/proto.users.v1.UsersService/GetAllUsers"
	// UsersServiceGetUserByIdProcedure is the fully-qualified name of the UsersService's GetUserById
	// RPC.
	UsersServiceGetUserByIdProcedure = "/proto.users.v1.UsersService/GetUserById"
	// UsersServiceCreateUserProcedure is the fully-qualified name of the UsersService's CreateUser RPC.
	UsersServiceCreateUserProcedure = "/proto.users.v1.UsersService/CreateUser"
	// UsersServiceUpdateUserProcedure is the fully-qualified name of the UsersService's UpdateUser RPC.
	UsersServiceUpdateUserProcedure = "/proto.users.v1.UsersService/UpdateUser"
	// UsersServiceDeleteUserProcedure is the fully-qualified name of the UsersService's DeleteUser RPC.
	UsersServiceDeleteUserProcedure = "/proto.users.v1.UsersService/DeleteUser"
)

// UsersServiceClient is a client for the proto.users.v1.UsersService service.
type UsersServiceClient interface {
	GetAllUsers(context.Context, *connect.Request[v1.GetAllUsersRequest]) (*connect.Response[v1.GetAllUsersResponse], error)
	GetUserById(context.Context, *connect.Request[v1.GetUserByIdRequest]) (*connect.Response[v1.GetUserByIdResponse], error)
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserByIdRequest]) (*connect.Response[v1.DeleteUserByIdResponse], error)
}

// NewUsersServiceClient constructs a client for the proto.users.v1.UsersService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewUsersServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) UsersServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	usersServiceMethods := v1.File_users_v1_users_proto.Services().ByName("UsersService").Methods()
	return &usersServiceClient{
		getAllUsers: connect.NewClient[v1.GetAllUsersRequest, v1.GetAllUsersResponse](
			httpClient,
			baseURL+UsersServiceGetAllUsersProcedure,
			connect.WithSchema(usersServiceMethods.ByName("GetAllUsers")),
			connect.WithClientOptions(opts...),
		),
		getUserById: connect.NewClient[v1.GetUserByIdRequest, v1.GetUserByIdResponse](
			httpClient,
			baseURL+UsersServiceGetUserByIdProcedure,
			connect.WithSchema(usersServiceMethods.ByName("GetUserById")),
			connect.WithClientOptions(opts...),
		),
		createUser: connect.NewClient[v1.CreateUserRequest, v1.CreateUserResponse](
			httpClient,
			baseURL+UsersServiceCreateUserProcedure,
			connect.WithSchema(usersServiceMethods.ByName("CreateUser")),
			connect.WithClientOptions(opts...),
		),
		updateUser: connect.NewClient[v1.UpdateUserRequest, v1.UpdateUserResponse](
			httpClient,
			baseURL+UsersServiceUpdateUserProcedure,
			connect.WithSchema(usersServiceMethods.ByName("UpdateUser")),
			connect.WithClientOptions(opts...),
		),
		deleteUser: connect.NewClient[v1.DeleteUserByIdRequest, v1.DeleteUserByIdResponse](
			httpClient,
			baseURL+UsersServiceDeleteUserProcedure,
			connect.WithSchema(usersServiceMethods.ByName("DeleteUser")),
			connect.WithClientOptions(opts...),
		),
	}
}

// usersServiceClient implements UsersServiceClient.
type usersServiceClient struct {
	getAllUsers *connect.Client[v1.GetAllUsersRequest, v1.GetAllUsersResponse]
	getUserById *connect.Client[v1.GetUserByIdRequest, v1.GetUserByIdResponse]
	createUser  *connect.Client[v1.CreateUserRequest, v1.CreateUserResponse]
	updateUser  *connect.Client[v1.UpdateUserRequest, v1.UpdateUserResponse]
	deleteUser  *connect.Client[v1.DeleteUserByIdRequest, v1.DeleteUserByIdResponse]
}

// GetAllUsers calls proto.users.v1.UsersService.GetAllUsers.
func (c *usersServiceClient) GetAllUsers(ctx context.Context, req *connect.Request[v1.GetAllUsersRequest]) (*connect.Response[v1.GetAllUsersResponse], error) {
	return c.getAllUsers.CallUnary(ctx, req)
}

// GetUserById calls proto.users.v1.UsersService.GetUserById.
func (c *usersServiceClient) GetUserById(ctx context.Context, req *connect.Request[v1.GetUserByIdRequest]) (*connect.Response[v1.GetUserByIdResponse], error) {
	return c.getUserById.CallUnary(ctx, req)
}

// CreateUser calls proto.users.v1.UsersService.CreateUser.
func (c *usersServiceClient) CreateUser(ctx context.Context, req *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return c.createUser.CallUnary(ctx, req)
}

// UpdateUser calls proto.users.v1.UsersService.UpdateUser.
func (c *usersServiceClient) UpdateUser(ctx context.Context, req *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return c.updateUser.CallUnary(ctx, req)
}

// DeleteUser calls proto.users.v1.UsersService.DeleteUser.
func (c *usersServiceClient) DeleteUser(ctx context.Context, req *connect.Request[v1.DeleteUserByIdRequest]) (*connect.Response[v1.DeleteUserByIdResponse], error) {
	return c.deleteUser.CallUnary(ctx, req)
}

// UsersServiceHandler is an implementation of the proto.users.v1.UsersService service.
type UsersServiceHandler interface {
	GetAllUsers(context.Context, *connect.Request[v1.GetAllUsersRequest]) (*connect.Response[v1.GetAllUsersResponse], error)
	GetUserById(context.Context, *connect.Request[v1.GetUserByIdRequest]) (*connect.Response[v1.GetUserByIdResponse], error)
	CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error)
	UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error)
	DeleteUser(context.Context, *connect.Request[v1.DeleteUserByIdRequest]) (*connect.Response[v1.DeleteUserByIdResponse], error)
}

// NewUsersServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewUsersServiceHandler(svc UsersServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	usersServiceMethods := v1.File_users_v1_users_proto.Services().ByName("UsersService").Methods()
	usersServiceGetAllUsersHandler := connect.NewUnaryHandler(
		UsersServiceGetAllUsersProcedure,
		svc.GetAllUsers,
		connect.WithSchema(usersServiceMethods.ByName("GetAllUsers")),
		connect.WithHandlerOptions(opts...),
	)
	usersServiceGetUserByIdHandler := connect.NewUnaryHandler(
		UsersServiceGetUserByIdProcedure,
		svc.GetUserById,
		connect.WithSchema(usersServiceMethods.ByName("GetUserById")),
		connect.WithHandlerOptions(opts...),
	)
	usersServiceCreateUserHandler := connect.NewUnaryHandler(
		UsersServiceCreateUserProcedure,
		svc.CreateUser,
		connect.WithSchema(usersServiceMethods.ByName("CreateUser")),
		connect.WithHandlerOptions(opts...),
	)
	usersServiceUpdateUserHandler := connect.NewUnaryHandler(
		UsersServiceUpdateUserProcedure,
		svc.UpdateUser,
		connect.WithSchema(usersServiceMethods.ByName("UpdateUser")),
		connect.WithHandlerOptions(opts...),
	)
	usersServiceDeleteUserHandler := connect.NewUnaryHandler(
		UsersServiceDeleteUserProcedure,
		svc.DeleteUser,
		connect.WithSchema(usersServiceMethods.ByName("DeleteUser")),
		connect.WithHandlerOptions(opts...),
	)
	return "/proto.users.v1.UsersService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case UsersServiceGetAllUsersProcedure:
			usersServiceGetAllUsersHandler.ServeHTTP(w, r)
		case UsersServiceGetUserByIdProcedure:
			usersServiceGetUserByIdHandler.ServeHTTP(w, r)
		case UsersServiceCreateUserProcedure:
			usersServiceCreateUserHandler.ServeHTTP(w, r)
		case UsersServiceUpdateUserProcedure:
			usersServiceUpdateUserHandler.ServeHTTP(w, r)
		case UsersServiceDeleteUserProcedure:
			usersServiceDeleteUserHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedUsersServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedUsersServiceHandler struct{}

func (UnimplementedUsersServiceHandler) GetAllUsers(context.Context, *connect.Request[v1.GetAllUsersRequest]) (*connect.Response[v1.GetAllUsersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.users.v1.UsersService.GetAllUsers is not implemented"))
}

func (UnimplementedUsersServiceHandler) GetUserById(context.Context, *connect.Request[v1.GetUserByIdRequest]) (*connect.Response[v1.GetUserByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.users.v1.UsersService.GetUserById is not implemented"))
}

func (UnimplementedUsersServiceHandler) CreateUser(context.Context, *connect.Request[v1.CreateUserRequest]) (*connect.Response[v1.CreateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.users.v1.UsersService.CreateUser is not implemented"))
}

func (UnimplementedUsersServiceHandler) UpdateUser(context.Context, *connect.Request[v1.UpdateUserRequest]) (*connect.Response[v1.UpdateUserResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.users.v1.UsersService.UpdateUser is not implemented"))
}

func (UnimplementedUsersServiceHandler) DeleteUser(context.Context, *connect.Request[v1.DeleteUserByIdRequest]) (*connect.Response[v1.DeleteUserByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("proto.users.v1.UsersService.DeleteUser is not implemented"))
}
